### ISSUE TITLE
Reload action is using name "reload" in wiki while registered as "reload_config"

### ISSUE THREAD

**Issue by SilverBut** [Luzifer/streamdeck#1]
In Wiki: 
![image](https://user-images.githubusercontent.com/6560655/97533277-e59d3f80-19f2-11eb-8f79-1e96632f148f.png)

While in the [code](https://github.com/Luzifer/streamdeck/blob/bee78d006c1fdd1a5afed3db06cd59190105593e/cmd/streamdeck/action_reload.go#L6):
```go
	registerAction("reload_config", actionReloadConfig{})
```

Maybe the wiki shall be changed?

BTW this project did what I was intended to do. I can help to write some features if you need.

**Comment by Luzifer** [comment]
Good catch! Thanks for notifying me. 🙂 - Fixed in Wiki.
