### ISSUE TITLE
pulseaudio connections are denied as user and root.

### ISSUE THREAD

**Issue by ColdfireDI** [Luzifer/streamdeck#11]
![2021-04-29-233448_2912x132_scrot](https://user-images.githubusercontent.com/29430595/116645325-95704d00-a943-11eb-835e-0689409384c0.png)

**Comment by Luzifer** [comment]
- Is there a PulseAudio server running as `root`?
- What does a `ls -lh /run/user/0/pulse/native` say?

**Comment by ColdfireDI** [comment]
i get a return message of "total 0"

**Comment by Luzifer** [comment]
Well, if there is no PulseAudio socket available, it's totally understandable the streamdeck application can't connect to it…
