### ISSUE TITLE
Not responding to future keypress event after timeout

### ISSUE THREAD

**Issue by SilverBut** [Luzifer/streamdeck#2]
After the time defined in `display_off_time`, it is not possible to bring up the display again by pressing any keys.

**Comment by SilverBut** [comment]
Maybe we should save current screen's index when turning to the blank page, and set all key's actions to swap back to the screen previously being displayed?

**Comment by Luzifer** [comment]
This should be fixed with `v1.2.0` - please have a look at the new version.

Also relative movement in the history is now possible: [action: `page`](https://github.com/Luzifer/streamdeck/wiki#page)

**Comment by SilverBut** [comment]
fix verified.
the new feature is charming!
